### PR TITLE
Fix/is relative default

### PR DESCRIPTION
**Pull request by drusc0**
@jthistle Hi James, I added the default return for the isRelative function. I was checking the statements and I was curious if this also adds the spouse as family? I am just starting to contribute to open source. Keep me in mind for future issues.

Thanks.

### CODE REVIEW

**Comment by jthistle** [comment]
Hi @drusc0 , thanks very much for your contribution! I'm quite surprised to get a contribution to be honest, seeing as I only started this a week ago, but it's great that this could help you get into open source a bit. Wasn't too long ago I was getting into open source as well :)

In regard to your PR - it looks good, but it would be great if you could squash your commits into one commit, preferably one with a more descriptive title. [This article has some details on this](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). I would do (if you're on Linux/Mac):

    git rebase HEAD~2 -i

Then, in the screen that comes up, change the first `pick` to `reword`, and the second `pick` to `squash`. A further screen should come up allowing you to change the commit message. Something that lets github automatically close the issue would be good: how about `fix #24: isRelative should return False as default` ?

Once again, thanks for your contribution! In the future, I would recommend looking at helping larger projects, where more people will be around to help and there'll be more things to do. Find a program that you really enjoy using/use a lot, and find out if you can contribute to it. For me it was MuseScore. For you, I don't know.

If you need any further help with rebasing and squashing, don't hesitate to comment here!

**Review by jthistle — APPROVED** [review]

**Comment by drusc0** [comment]
ok sorry about that. I didn't realize this was in 2 different commits.

I wasnt sure about the standards of what needs to go on the description. So I should add the "issue number" prefixed with fix, and the action that I took. Is there anything else that should go on the description? What let's github know this case is fix to close it automatically (is it "fix: #24")?

Thanks for the guidance.

**Comment by drusc0** [comment]
after rebasing, do I need to push or commit? this is not automatically shown here correct?

**Comment by jthistle** [comment]
right, you've done what I would have done before I learned what was going wrong. It's quite hard to explain how to fix it, so jnstead, I'll merge your changes but I'll do the rebasing myself. Thanks again for your contribution, and I hope you can find other projects that perhaps have more issues and better support :)

**Pull request merged**
